### ISSUE TITLE
defineNuxtPlugin is not found 

### ISSUE THREAD

**Issue by briandee** [csprance/nuxt3-pino#2]
Looking at the Nuxt plugin documentation, plugins are only read if they are defined in the plugins directory.  Since the plugins defined in the code are in the runtime folder they will not be scanned.  When I install and attempt to use the plugin in a Nuxt 3.10.0 app it fails with the following:

[nuxt] [request error] [unhandled] [500] defineNuxtPlugin is not defined
  at ./node_modules/nuxt3-pino/dist/runtime/pino.server.mjs:3:1  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ViteNodeRunner.runModule (/Users/g4792/Desktop/care-locationdata-ui/node_modules/vite-node/dist/client.mjs:362:5)  
  at async ViteNodeRunner.directRequest (/Users/g4792/Desktop/care-locationdata-ui/node_modules/vite-node/dist/client.mjs:346:5)  
  at async ViteNodeRunner.cachedRequest (/Users/g4792/Desktop/care-locationdata-ui/node_modules/vite-node/dist/client.mjs:189:14)

**Comment by paambaati** [comment]
@csprance Facing the same issue.

**Comment by csprance** [comment]
It will be a bit before I can get to this. If you send a PR I'm happy to merge it.

**Comment by agracia-foticos** [comment]
same issue!

ReferenceError {
  stack: 'defineNuxtPlugin is not defined\n' +
  'at /home/app/var/www/web/node_modules/nuxt3-pino/dist/runtime/pino.server.mjs:3:37)\n' +
  '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
  'at async ViteNodeRunner.runModule (/home/app/var/www/web/node_modules/vite-node/dist/client.mjs:354:3)\n' +
  'at async ViteNodeRunner.directRequest (/home/app/var/www/web/node_modules/vite-node/dist/client.mjs:333:3)\n' +
  'at async ViteNodeRunner.cachedRequest (/home/app/var/www/web/node_modules/vite-node/dist/client.mjs:168:11)\n' +
  'at async ViteNodeRunner.dependencyRequest (/home/app/var/www/web/node_modules/vite-node/dist/client.mjs:216:10)\n' +
  'at async ./virtual:nuxt:%2Fhome%2Fapp%2Fvar%2Fwww%2Fweb%2Fapps%2Fwanapix-ecommerce%2F.nuxt%2Fplugins.server.mjs:14:32)\n' +
  'at async ViteNodeRunner.runModule (/home/app/var/www/web/node_modules/vite-node/dist/client.mjs:354:3)\n' +
  'at async ViteNodeRunner.directRequest (/home/app/var/www/web/node_modul'... 147 more characters,
  message: 'defineNuxtPlugin is not defined',
}
